import '../globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import SidBar from '../component/SidBar'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SidBar/>
        {children}
        </body>
    </html>
  )
}
